version: '3'

services:
  app:
    build: .
    container_name: talentuzz-app
    tty: true
    ports:
      - ${PORT}:${PORT}
      - 5555:5555
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_HOST}

volumes:
  db:
